name: "latest-release"

on:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  latest-release-linux:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: init rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      
      - name: build release binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      
      - name: create release artifacts
        run: |
          ls -R . && \
          python3 ./release.py
      
      - name: publish release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            blynk_latest.zip
          draft: true
